version: '3'
services:
  postgresql:
    image: postgres:13-alpine
    restart: on-failure
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: '${DB_PASSWORD}'
      POSTGRES_USER: '${DB_USER}'
      POSTGRES_DB: '${DB_NAME}'
    volumes:
      - pgsql:/var/lib/postgresql/data
    networks:
      - service

networks:
  service:
    driver: bridge

volumes:
  pgsql:
    driver: local